spring.application.name=lootdrop
server.port=8080

# neon veritabani baglantisi (Neon)

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / Hibernate ayarlari
# update: tablolari otomatik olarak gunceller (!!!dev ortami icin iyi prod ortaminda validate kullan!!!!)
spring.jpa.hibernate.ddl-auto=update
# SQL sorgularini gorebilmek icin, silinebilir
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect